apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-ingress-controller-admin
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: ledboot-ingress
roleRef:
  kind: ClusterRole
  name: knative-ingress-admin
  apiGroup: rbac.authorization.k8s.io