apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: ledboot-ingress
data:
  loglevel.controller: "info"
  zap-logger-config: |
    {
      "level": "info",
      "development": true,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
